# config.toml
# https://github.com/CrimsonRay/slender

baseurl = "//eisenbarth.io/"
#baseurl = "localhost"
title = "Jean-Philippe Eisenbarth"
languageCode = "fr_FR"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"
PygmentsUseClasses = false
PygmentsStyle = "monokai"
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 1
    [languages.fr.params]
      linkedin = 'https://fr.linkedin.com/fr/eisenbarth'
      [languages.fr.params.navigation]
        home = 'Accueil'
    [[languages.fr.menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 0
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2
    [languages.en.params]
      linkedin = 'https://linkedin.com/eisenbarth'
      [languages.en.params.navigation]
        home = 'Home'
    [[languages.en.menu.main]]
      identifier = "accueil"
        name = "Home"
        url = "/"
        weight = 0


[author]
    name = "Jean-Philippe Eisenbarth"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "<cite>A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.</cite> Leslie Lamport"

    # Footer; Markdown accepted here.
    footer = "Construit avec Hugo (https://gohugo.io/)"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Default Page Description"
    keywords = "default,page,keywords"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    # email = "mailto:your-email"
    github = "https://github.com/jpeisenbarth"
    # bitbucket = "url-to-your-bitbucket"
    # twitter = "url-to-your-twitter"
    # stackoverflow = "url-to-your-stackoverflow"
    linkedin = "https://fr.linkedin.com/in/eisenbarth"
    # facebook = "url-to-your-facebook"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    # ganalytics = "your-google-analytics-tracking-code"
